AllCops:
  Exclude:
    - 'assets/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'build/**/*'
    - 'ext/**/*'
    - '**/Rakefile'
    - '**/*.gemspec'
  NewCops: enable
  TargetRubyVersion: 3.1

Naming/MethodParameterName:
  inherit_mode:
    override:
      - Include
  AllowedNames:
    - x
    - y
    - z
    - x1
    - y1
    - x2
    - y2
    - x3
    - y3
    - x4
    - y4
    - dx
    - dy
    - dz
    - as

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
  Max: 1024

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 32

Metrics/ParameterLists:
  Max: 16

Layout/LineLength:
  Max: 200

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  