# frozen_string_literal: true

# Ruby2D module and native extension loader
unless RUBY_ENGINE == 'mruby'
  require 'ruby2d/cvs/cvs'
  include Ruby2D::CVS
  require 'ruby2d/extensions'
  require 'ruby2d/utils'
  require 'ruby2d/planned'
  require 'ruby2d/cli/colorize'
  require 'ruby2d/exceptions'
  require 'ruby2d/draw/render/renderable'
  require 'ruby2d/draw/color'
  require 'ruby2d/compose/entity'
  require 'ruby2d/compose/cluster'
  require 'ruby2d/compose/arena/arena'
  require 'ruby2d/draw/render/quad'
  require 'ruby2d/draw/render/line'
  require 'ruby2d/draw/render/circle'
  require 'ruby2d/draw/render/rectangle'
  require 'ruby2d/draw/render/square'
  require 'ruby2d/draw/render/triangle'
  require 'ruby2d/draw/pixel'
  require 'ruby2d/draw/pixmap'
  require 'ruby2d/draw/pixmap_atlas'
  require 'ruby2d/draw/render/image'
  require 'ruby2d/draw/render/sprite'
  require 'ruby2d/draw/tileset'
  require 'ruby2d/draw/font'
  require 'ruby2d/draw/render/text'
  require 'ruby2d/draw/render/canvas'
  require 'ruby2d/sound'
  require 'ruby2d/music'
  require 'ruby2d/draw/texture'
  require 'ruby2d/draw/vertices'
  require 'ruby2d/outfit'
  require 'ruby2d/compose/widget'
  require 'ruby2d/compose/arrange/grid'
  require 'ruby2d/compose/arrange/fit_grid'
  require 'ruby2d/compose/arrange/gap'
  require 'ruby2d/compose/arrange/col_row_container'
  require 'ruby2d/compose/arrange/col'
  require 'ruby2d/compose/arrange/row'
  require 'ruby2d/compose/arrange/box_container'
  require 'ruby2d/compose/button'
  require 'ruby2d/compose/note'
  require 'ruby2d/compose/ruby_note'
  require 'ruby2d/compose/note_support'
  require 'ruby2d/compose/album'
  require 'ruby2d/compose/arena/form'
  require 'ruby2d/compose/arena/table'
  require 'ruby2d/window'
  require 'ruby2d/dsl'
  require 'ruby2d/ruby2d' # load native extension
end
